services:
  db:
    image: postgres:17.5
    container_name: smkn4-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=type&writer
      - POSTGRES_DB=profilsmkn4
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  backend:
    build: .
    container_name: smkn4-backend
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules # Hindari overwrite node_modules
    env_file:
      - .env
    command: sh -c "npx prisma db push && npm run dev"

volumes:
  db_data:    

    